export const SCHEMA = 1;

export const TASK_STATUSES = [
  { id: 'todo', label: '代办' },
  { id: 'doing', label: '进行中' },
  { id: 'blocked', label: '阻塞' },
  { id: 'verify', label: '待验证' },
  { id: 'done', label: '已完成' },
  { id: 'abandoned', label: '放弃' },
];

export const BUG_STATUSES = [
  { id: 'open', label: '待修复' },
  { id: 'fixing', label: '修复中' },
  { id: 'fixed', label: '已修复' },
  { id: 'invalid', label: '已无关' },
];

export const MILESTONE_STATUSES = [
  { id: 'done', label: '已完成' },
  { id: 'current', label: '当前' },
  { id: 'upcoming', label: '未到达' },
];

function task(partial) {
  return {
    blockReason: '',
    endedAt: '',
    autoComplete: true,
    autoCompleted: false,
    focus: null,
    checks: [],
    subtasks: [],
    dependsOn: [],
    fromIdeaId: null,
    ...partial,
  };
}

export function createSeed() {
  const projects = [
    {
      id: 'p_xinggang',
      name: '星港余烬',
      description: '俯视角动作 Demo。先把移动手感和战斗连段做扎实，再考虑关卡。',
      tags: { k_type: 'tv_action', k_platform: 'pv_win', k_version: 'vv_02' },
      modules: [
        { id: 'm_combat', name: '战斗系统' },
        { id: 'm_move', name: '移动系统' },
        { id: 'm_bag', name: '背包系统' },
        { id: 'm_cam', name: '镜头系统' },
      ],
      versions: [
        { id: 'ver_xg_01', name: 'v0.1', title: '移动原型' },
        { id: 'ver_xg_02', name: 'v0.2', title: '战斗循环' },
      ],
      milestones: [
        { id: 'ms_move', name: '移动手感可玩', versionId: 'ver_xg_01', status: 'done' },
        { id: 'ms_combo', name: '基础攻击连段', versionId: 'ver_xg_02', status: 'current' },
        { id: 'ms_level', name: '第一关可通关', versionId: 'ver_xg_02', status: 'upcoming' },
        { id: 'ms_build', name: '对外试玩包', versionId: 'ver_xg_02', status: 'upcoming' },
      ],
      tasks: [
        task({
          id: 't_wasd',
          versionId: 'ver_xg_01',
          moduleId: 'm_move',
          title: '八向移动',
          description: '键盘和手柄都能走出稳定的八向，斜向不能比直线更快。',
          status: 'done',
          createdAt: '2026-09-12T09:20',
          endedAt: '2026-09-16T18:05',
          updatedAt: '2026-09-16T18:05',
          autoCompleted: true,
          checks: [{ id: 'c_diag', text: '斜向速度已归一', done: true }],
          subtasks: [
            { id: 's_wasd', title: 'WASD 输入', description: '同时按两个方向要合成斜向。', done: true },
            { id: 's_stick', title: '手柄左摇杆', description: '死区大约 0.18。', done: true },
          ],
        }),
        task({
          id: 't_accel',
          versionId: 'ver_xg_01',
          moduleId: 'm_move',
          title: '加速度曲线',
          description: '起步不要一下子满速，停步可以稍快，避免发飘。',
          status: 'done',
          createdAt: '2026-09-13T11:00',
          endedAt: '2026-09-18T16:40',
          updatedAt: '2026-09-18T16:40',
          autoCompleted: true,
          subtasks: [{ id: 's_curve', title: '调一条起步和刹车曲线', description: '', done: true }],
        }),
        task({
          id: 't_dash_move',
          versionId: 'ver_xg_01',
          moduleId: 'm_move',
          title: '冲刺位移',
          description: '短距离、固定时长，不吃摇杆长度。',
          status: 'done',
          createdAt: '2026-09-14T15:10',
          endedAt: '2026-09-20T12:12',
          updatedAt: '2026-09-20T12:12',
          subtasks: [{ id: 's_dash_dist', title: '定好冲刺距离和时长', description: '大约 3.2 米、0.18 秒。', done: true }],
        }),
        task({
          id: 't_wall',
          versionId: 'ver_xg_01',
          moduleId: 'm_move',
          title: '撞墙滑开',
          description: '贴墙移动要顺着墙滑，不要粘住。',
          status: 'done',
          createdAt: '2026-09-18T10:05',
          endedAt: '2026-09-22T19:30',
          updatedAt: '2026-09-22T19:30',
        }),
        task({
          id: 't_dash_cd',
          versionId: 'ver_xg_01',
          moduleId: 'm_move',
          title: '冲刺冷却提示',
          description: '冷却没转完时，按冲刺只抖一下，不要再次位移。',
          status: 'doing',
          createdAt: '2026-09-21T14:22',
          endedAt: '',
          updatedAt: '2026-09-28T11:05',
          focus: 'today',
          checks: [{ id: 'c_no_redash', text: '冷却中不能再次冲刺', done: true }],
          subtasks: [
            { id: 's_cd_num', title: '冷却数字', description: '显示剩余秒数，一位小数。', done: true },
            { id: 's_cd_key', title: '按键提示', description: '键位图标在冷却时变灰。', done: false },
          ],
        }),
        task({
          id: 't_light',
          versionId: 'ver_xg_02',
          moduleId: 'm_combat',
          title: '轻攻击三段',
          description: '地面轻攻击三连，第三段有一点前冲。',
          status: 'done',
          createdAt: '2026-09-19T09:40',
          endedAt: '2026-09-25T17:15',
          updatedAt: '2026-09-25T17:15',
          autoCompleted: true,
          checks: [{ id: 'c_chain', text: '段与段之间可以取消后摇', done: true }],
          subtasks: [
            { id: 's_atk1', title: '第一段劈砍', description: '', done: true },
            { id: 's_atk2', title: '第二段横扫', description: '', done: true },
            { id: 's_atk3', title: '第三段前冲', description: '', done: true },
          ],
        }),
        task({
          id: 't_face',
          versionId: 'ver_xg_02',
          moduleId: 'm_combat',
          title: '攻击时锁定朝向',
          description: '出招瞬间朝向最近的敌人，招式中途不再跟着摇杆转。',
          status: 'done',
          createdAt: '2026-09-20T13:12',
          endedAt: '2026-09-26T18:48',
          updatedAt: '2026-09-26T18:48',
        }),
        task({
          id: 't_combo',
          versionId: 'ver_xg_02',
          moduleId: 'm_combat',
          title: '连击判定窗口',
          description: '两段攻击之间留一个固定窗口，超时就断连。',
          status: 'done',
          createdAt: '2026-09-22T10:18',
          endedAt: '2026-09-27T21:05',
          updatedAt: '2026-09-27T21:05',
          dependsOn: ['t_light'],
        }),
        task({
          id: 't_hit',
          versionId: 'ver_xg_02',
          moduleId: 'm_combat',
          title: '受击硬直与击退',
          description: '被打中要有明确的硬直，击退不要把人推进墙里。',
          status: 'blocked',
          blockReason: '击退距离和墙体碰撞还没定，先不铺受击动画。',
          createdAt: '2026-09-23T16:02',
          endedAt: '',
          updatedAt: '2026-09-28T09:40',
          focus: 'week',
          dependsOn: ['t_light'],
        }),
        task({
          id: 't_dodge',
          versionId: 'ver_xg_02',
          moduleId: 'm_combat',
          title: '完美闪避',
          description: '在受击判定前的一小段窗口里闪避，算完美闪避。',
          status: 'todo',
          createdAt: '2026-09-26T11:28',
          endedAt: '',
          updatedAt: '2026-09-26T11:28',
          focus: 'today',
          fromIdeaId: 'i_slow',
          dependsOn: ['t_hit'],
          subtasks: [
            { id: 's_window', title: '闪避窗口 8 帧', description: '先写死，手感不对再改。', done: false },
            { id: 's_slow', title: '成功时短暂停顿', description: '大约 0.12 秒，不要做成电影。', done: false },
          ],
        }),
        task({
          id: 't_loot',
          versionId: 'ver_xg_02',
          moduleId: 'm_bag',
          title: '拾取飞向角色',
          description: '掉落物先停一下，再飞进角色身上。',
          status: 'done',
          createdAt: '2026-09-17T15:45',
          endedAt: '2026-09-24T12:20',
          updatedAt: '2026-09-24T12:20',
        }),
        task({
          id: 't_hotbar',
          versionId: 'ver_xg_02',
          moduleId: 'm_bag',
          title: '消耗品快捷栏',
          description: '四个格子，战斗里能直接用药。',
          status: 'doing',
          createdAt: '2026-09-24T19:05',
          endedAt: '',
          updatedAt: '2026-09-27T20:16',
          focus: 'week',
          checks: [{ id: 'c_slot', text: '空格子不能触发', done: false }],
        }),
        task({
          id: 't_drag_drop',
          versionId: 'ver_xg_01',
          moduleId: 'm_bag',
          title: '格子拖拽方案',
          description: '试过一整页拖拽背包，演示时太重，先放弃。',
          status: 'abandoned',
          createdAt: '2026-09-15T10:12',
          endedAt: '2026-09-19T09:00',
          updatedAt: '2026-09-19T09:00',
          autoComplete: false,
        }),
        task({
          id: 't_follow',
          versionId: 'ver_xg_02',
          moduleId: 'm_cam',
          title: '镜头跟随与死区',
          description: '角色在屏幕中心附近小范围活动时，镜头不要抖。',
          status: 'todo',
          createdAt: '2026-09-25T08:50',
          endedAt: '',
          updatedAt: '2026-09-25T08:50',
          focus: 'week',
        }),
        task({
          id: 't_shake',
          versionId: 'ver_xg_02',
          moduleId: 'm_cam',
          title: '受击震屏',
          description: '只有受击和第三段攻击震，平时保持稳。',
          status: 'verify',
          createdAt: '2026-09-26T17:33',
          endedAt: '',
          updatedAt: '2026-09-28T15:02',
          dependsOn: ['t_hit'],
          checks: [{ id: 'c_shake', text: '连续受击不会把镜头甩飞', done: false }],
        }),
        task({
          id: 't_zoom',
          versionId: 'ver_xg_02',
          moduleId: 'm_cam',
          title: '冲刺时轻微拉远',
          description: '冲刺开始拉远一点，结束回到原位。',
          status: 'todo',
          createdAt: '2026-09-27T13:14',
          endedAt: '',
          updatedAt: '2026-09-27T13:14',
        }),
      ],
      bugs: [
        {
          id: 'b_ne',
          moduleId: 'm_combat',
          name: '东北朝向吞掉收招',
          summary: '角色面向东北时，轻攻击第三段会跳过收招，直接回到待机。',
          status: 'fixing',
          createdAt: '2026-09-26T20:11',
          updatedAt: '2026-09-28T10:02',
        },
        {
          id: 'b_wall',
          moduleId: 'm_move',
          name: '贴墙冲刺卡进碰撞体',
          summary: '对着墙角冲刺时，胶囊体会留在墙里面，要连按两下才弹出来。',
          status: 'open',
          createdAt: '2026-09-22T18:26',
          updatedAt: '2026-09-22T18:26',
        },
        {
          id: 'b_count',
          moduleId: 'm_bag',
          name: '快捷栏数字和背包不一致',
          summary: '用药之后快捷栏减了，背包格子还显示旧数量。已在拾取飞入后顺手对过一次账。',
          status: 'fixed',
          createdAt: '2026-09-21T12:08',
          updatedAt: '2026-09-25T16:44',
        },
        {
          id: 'b_dummy',
          moduleId: 'm_combat',
          name: '拆掉的木桩仍会被锁敌',
          summary: '训练场木桩移除后，锁敌列表里还留着它的 id。这套木桩已经不用了。',
          status: 'invalid',
          createdAt: '2026-09-18T09:16',
          updatedAt: '2026-09-23T11:20',
        },
      ],
      ideas: [
        {
          id: 'i_dur',
          title: '武器会磨损',
          body: '打久了刀刃变钝，伤害掉一截，得回营地磨。不想做成经营，只是让一把武器有寿命。',
          status: 'open',
          createdAt: '2026-09-20T21:18',
          updatedAt: '2026-09-20T21:18',
          tagIds: ['iv_feel', 'iv_keep'],
          taskId: null,
        },
        {
          id: 'i_box',
          title: '箱子可以被砸开',
          body: '战斗里的木箱不是装饰。第三段攻击能把箱子砸开，里面偶尔有药。',
          status: 'open',
          createdAt: '2026-09-23T22:05',
          updatedAt: '2026-09-23T22:05',
          tagIds: ['iv_level', 'iv_later'],
          taskId: null,
        },
        {
          id: 'i_slow',
          title: '闪避成功时短暂慢动作',
          body: '完美闪避命中的那一下，世界慢下来一点点，好让自己知道躲对了。',
          status: 'converted',
          createdAt: '2026-09-25T23:40',
          updatedAt: '2026-09-26T11:28',
          tagIds: ['iv_look', 'iv_keep'],
          taskId: 't_dodge',
        },
        {
          id: 'i_call',
          title: '同伴喊出连击数',
          body: '连到五段以上时，旁边的人喊一句。喊太勤会烦，只在整五段喊。',
          status: 'open',
          createdAt: '2026-09-27T00:12',
          updatedAt: '2026-09-27T00:12',
          tagIds: ['iv_look', 'iv_later'],
          taskId: null,
        },
        {
          id: 'i_rain',
          title: '雨天甲板打滑',
          body: '下雨时刹车变长，冲刺尾端会多滑一小步。只想在一关里用，不做成全局天气系统。',
          status: 'open',
          createdAt: '2026-09-28T08:36',
          updatedAt: '2026-09-28T08:36',
          tagIds: ['iv_feel', 'iv_later'],
          taskId: null,
        },
      ],
      notes: [
        {
          id: 'n_startup',
          title: '攻击前摇',
          body: '轻攻击前摇不要超过 6 帧，不然三段连起来会发软。',
          createdAt: '2026-09-19T21:00',
          updatedAt: '2026-09-19T21:00',
        },
        {
          id: 'n_iframe',
          title: '冲刺无敌',
          body: '无敌只覆盖冲刺的前半段。落地之后可以被抓，避免穿怪。',
          createdAt: '2026-09-21T22:14',
          updatedAt: '2026-09-21T22:14',
        },
      ],
    },
    {
      id: 'p_boat',
      name: '纸船',
      description: '把一张纸折成船，让它漂过墨水画出来的海。操作尽量少。',
      tags: { k_type: 'tv_puzzle', k_platform: 'pv_win', k_version: 'vv_boat' },
      modules: [
        { id: 'm_flow', name: '水流系统' },
        { id: 'm_fold', name: '折纸系统' },
      ],
      versions: [{ id: 'ver_boat_01', name: 'v0.1', title: '第一张海图' }],
      milestones: [
        { id: 'ms_flow', name: '船能顺着水流走', versionId: 'ver_boat_01', status: 'done' },
        { id: 'ms_wind', name: '风会把船掀翻', versionId: 'ver_boat_01', status: 'current' },
      ],
      tasks: [
        task({
          id: 't_flow',
          versionId: 'ver_boat_01',
          moduleId: 'm_flow',
          title: '沿水流移动',
          description: '船贴着墨线走，玩家只在岔口拨一下。',
          status: 'done',
          createdAt: '2026-09-11T10:00',
          endedAt: '2026-09-17T15:30',
          updatedAt: '2026-09-17T15:30',
          autoCompleted: true,
          subtasks: [{ id: 's_fork', title: '岔口拨向', description: '', done: true }],
        }),
        task({
          id: 't_fold',
          versionId: 'ver_boat_01',
          moduleId: 'm_fold',
          title: '折一条能浮的船',
          description: '三步折完。步数再多，演示时没人愿意看。',
          status: 'doing',
          createdAt: '2026-09-18T14:20',
          endedAt: '',
          updatedAt: '2026-09-27T19:10',
          focus: 'week',
          subtasks: [
            { id: 's_step1', title: '对折', description: '', done: true },
            { id: 's_step2', title: '折出船头', description: '', done: false },
          ],
        }),
        task({
          id: 't_ink',
          versionId: 'ver_boat_01',
          moduleId: 'm_flow',
          title: '墨水慢慢晕开',
          description: '海图边缘会晕开，晕开的地方船走得更慢。',
          status: 'todo',
          createdAt: '2026-09-28T16:42',
          endedAt: '',
          updatedAt: '2026-09-28T16:42',
        }),
      ],
      bugs: [
        {
          id: 'b_flip',
          moduleId: 'm_flow',
          name: '急弯处船会翻面',
          summary: '弯太急时船的正面翻到了纸背面，再拨也回不来。',
          status: 'open',
          createdAt: '2026-09-27T11:18',
          updatedAt: '2026-09-27T11:18',
        },
      ],
      ideas: [
        {
          id: 'i_crease',
          title: '折痕当成存档点',
          body: '每折完一步就落一处折痕。翻船后从最后一道折痕重新漂。',
          status: 'open',
          createdAt: '2026-09-24T20:00',
          updatedAt: '2026-09-24T20:00',
          tagIds: ['iv_system', 'iv_keep'],
          taskId: null,
        },
        {
          id: 'i_drop',
          title: '雨点把海图打湿',
          body: '雨点落下的地方墨线会断。不一定做，先记着。',
          status: 'open',
          createdAt: '2026-09-26T09:24',
          updatedAt: '2026-09-26T09:24',
          tagIds: ['iv_level', 'iv_later'],
          taskId: null,
        },
      ],
      notes: [
        {
          id: 'n_steps',
          title: '折纸步数',
          body: '折纸步骤最多三步，多了演示会劝退。',
          createdAt: '2026-09-18T14:00',
          updatedAt: '2026-09-18T14:00',
        },
      ],
    },
  ];

  const tagKinds = [
    {
      id: 'k_type',
      domain: 'project',
      name: '类型',
      color: '#7c5cbf',
      slot: 1,
      bindVersions: false,
      values: [
        { id: 'tv_none', name: '无' },
        { id: 'tv_action', name: '动作' },
        { id: 'tv_puzzle', name: '解谜' },
        { id: 'tv_story', name: '叙事' },
      ],
    },
    {
      id: 'k_platform',
      domain: 'project',
      name: '平台',
      color: '#2f7d9a',
      slot: 2,
      bindVersions: false,
      values: [
        { id: 'pv_win', name: 'Windows' },
        { id: 'pv_and', name: 'Android' },
        { id: 'pv_mac', name: 'Mac' },
        { id: 'pv_linux', name: 'Linux' },
      ],
    },
    {
      id: 'k_version',
      domain: 'project',
      name: '版本',
      color: '#b8860b',
      slot: 3,
      bindVersions: true,
      values: [
        { id: 'vv_01', name: 'v0.1', projectId: 'p_xinggang' },
        { id: 'vv_02', name: 'v0.2', projectId: 'p_xinggang' },
        { id: 'vv_boat', name: 'v0.1', projectId: 'p_boat' },
      ],
    },
    {
      id: 'k_spark',
      domain: 'idea',
      name: '灵感',
      color: '#c46b3a',
      slot: 0,
      bindVersions: false,
      values: [
        { id: 'iv_feel', name: '手感' },
        { id: 'iv_level', name: '关卡' },
        { id: 'iv_system', name: '系统' },
        { id: 'iv_look', name: '表现' },
      ],
    },
    {
      id: 'k_keep',
      domain: 'idea',
      name: '去留',
      color: '#3d8b6e',
      slot: 0,
      bindVersions: false,
      values: [
        { id: 'iv_keep', name: '想做' },
        { id: 'iv_later', name: '先记着' },
      ],
    },
  ];

  return {
    schema: SCHEMA,
    settings: {
      theme: 'dark',
      github: {
        url: 'https://github.com/local/xinggang-embers',
        branch: 'main',
        username: 'local',
        token: 'mock-token',
        remembered: true,
      },
    },
    tagKinds,
    projects,
    trash: [],
    git: {
      branch: 'main',
      ahead: 0,
      behind: 1,
      commitMessage: '',
      staged: {},
      base: {},
      incoming: [
        {
          projectId: 'p_xinggang',
          path: 'projects/p_xinggang/milestones.json',
          summary: '远端新增里程碑「可玩原型」',
          milestone: {
            id: 'ms_playable',
            name: '可玩原型',
            versionId: 'ver_xg_02',
            status: 'upcoming',
          },
        },
      ],
      commits: [
        {
          id: 'c_seed',
          message: '记下移动原型的冲刺距离',
          at: '2026-09-27T21:40',
          pushed: true,
          files: ['projects/p_xinggang/tasks.json'],
        },
      ],
    },
    ui: {
      activity: 'projects',
      sidebarOpen: true,
      sidebarWidth: 268,
      scmOpen: false,
      projectId: 'p_xinggang',
      tab: 'dashboard',
      tabOrder: ['dashboard', 'list', 'kanban', 'bugs', 'ideas'],
      projectSettings: false,
      search: '',
      quickOpen: false,
      listVersion: 'ver_xg_02',
      sortMode: 'status',
      sortDir: 'asc',
      statusOrder: ['todo', 'doing', 'blocked', 'verify', 'done', 'abandoned'],
      statusFilter: 'all',
      expanded: { t_dash_cd: true },
      kanbanVersion: 'ver_xg_02',
      kanbanMode: 'board',
      graphTaskId: 't_dodge',
      ideaLayout: 'order',
      ideaSort: 'created',
      ideaDir: 'desc',
      ideaQuery: '',
      ideaStatus: 'all',
      settingsAnchor: 'appearance',
      pendingScroll: '',
      scmSelected: '',
      bugDrafts: {},
    },
  };
}
